Повторение Pandas, Matplotlib

Начнем с повторения библотек Pandas и Matplotlib. В ML Pandas нужен для работы с данными, а Matplotlib для быстрой визуализации и проверки результата.

In [4]:
# скачиваем пандас с флагом -q (тихо, без терминала)
!pip install -q pandas

In [5]:
import pandas as pd

In [9]:
# прочитаем файл comma-separated values
df = pd.read_csv('/content/sample_data/mnist_test.csv')

In [13]:
df.head()

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
df.shape

(9999, 785)

In [17]:
df1 = df['0']
df1.head()

0    0
1    0
2    0
3    0
4    0
Name: 0, dtype: int64

In [20]:
df2 = df[['0', '0.1', '1.3']]
df2.head()

KeyError: "['1.3'] not in index"

Ошибка KeyError - значит, что таких значений нету в столбцах

In [21]:
df2 = df[['0', '0.1', '0.3']]
df2.head()

   0  0.1  0.3
0  0    0    0
1  0    0    0
2  0    0    0
3  0    0    0
4  0    0    0

In [23]:
# создание гугл таблицы (оффтоп)
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df2)

https://docs.google.com/spreadsheets/d/1hzYLEzz37vOT0NlGlPsxdkO2XnsrCWXCEhhwjV0DFJw/edit#gid=0

In [31]:
# & - это логический оператор "И"
# | - это "ИЛИ"
# ~ - это "НЕ"

df3 = df2[(df2['0.1'] == 0) & (df2['0.1'] == 0)]
df3

      0  0.1  0.3
0     0    0    0
1     0    0    0
2     0    0    0
3     0    0    0
4     0    0    0
...  ..  ...  ...
9994  0    0    0
9995  0    0    0
9996  0    0    0
9997  0    0    0
9998  0    0    0

[9999 rows x 3 columns]

In [32]:
# сколько none значений
df2.isna().sum()

0      0
0.1    0
0.3    0
dtype: int64

In [34]:
series1 = pd.Series(['None', '1', '2'])

In [36]:
series1

0    None
1       1
2       2
dtype: object

In [35]:
series1.isna()

0    False
1    False
2    False
dtype: bool

О, тут я ошибся... Надо было None без кавычек

In [38]:
series1 = pd.Series([None, '1', '2'])

In [39]:
series1.isna()

0     True
1    False
2    False
dtype: bool

In [40]:
s2 = series1.dropna()
s2

1    1
2    2
dtype: object

In [41]:
s3 = series1.fillna(0)
s3

0    0
1    1
2    2
dtype: object

In [46]:
# и наоборот, посмотрим те что не None
s3 = series1.notna()
s3

0    False
1     True
2     True
dtype: bool

In [49]:
x = {
    'Name': ['Rinat', 'Nikita', 'Kiril'],
    'Age': ['21', '23', '24']
}
ex1 = pd.DataFrame(x)
ex1

     Name Age
0   Rinat  21
1  Nikita  23
2   Kiril  24

In [52]:
y = {
    'Name': ['Rinat', 'Nikita', 'Kiril'],
    'Salary': ['200000', '100000', '300000']
}

ex2 = pd.DataFrame(y)
ex2

     Name  Salary
0   Rinat  200000
1  Nikita  100000
2   Kiril  300000

In [64]:
df_search = ex2['Name'].str.contains('Rinat')
df_search[df_search == True]

0    True
Name: Name, dtype: bool

In [ ]:
import matplotlib.pyplot as plt